<a href="https://colab.research.google.com/github/ignadr/ML-Algorithms-Manual/blob/main/multiple_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math
import matplotlib.pyplot as plt

In [ ]:
# Mock data
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

print(X_train)
print(X_train.shape)
print(y_train)
print(y_train.shape)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
(3, 4)
[460 232 178]
(3,)


In [ ]:
# Mock w and b
w_init = np.array([ 1, 15, -45, -19])
b_init = 600

# From the course
# b_init = 785.1811367994083
# w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

print(w_init)
print(w_init.shape)
print(b_init)

[  1  15 -45 -19]
(4,)
600


## Prediction for a single row

In [ ]:
def compute_multiple_linear_model(x, w, b):
  # Single feature prediction using vectorization
  f_wb = np.dot(x, w) + b

  return f_wb

In [ ]:
print(f"Prediction for row 1: {compute_multiple_linear_model(X_train[0, :], w_init, b_init)}")

Prediction for row 1: 1879


## Cost function

In [ ]:
def compute_cost(x, y, w, b):
  m = x.shape[0]

  cost_sum = 0

  for i in range(m):
    f_wb = np.dot(x[i], w) + b
    cost_sum = cost_sum + ((f_wb - y[i]) ** 2)

  total_cost = cost_sum / (2 * m)

  return total_cost

In [ ]:
print(f"Current cost: {compute_cost(X_train, y_train, w_init, b_init)}")

Current cost: 554139.6666666666


## Gradient Descent

In [ ]:
def compute_gradient(x, y, w, b):
  m, n = x.shape
  dj_dw = np.zeros((n,))
  dj_db = 0

  # Iterate through all rows
  for i in range(m):
    err = np.dot(x[i], w) + b - y[i]

    # Iterate through all features
    for j in range(n):
      dj_dw[j] = dj_dw[j] + err * x[i, j]

    dj_db = dj_db + err

  dj_dw = dj_dw / m
  dj_db = dj_db / m

  return dj_dw, dj_db

In [ ]:
def gradient_descent(x, y, w_init, b_init, alpha, num_iter, cost_function, gradient_function):
  J_hist = []

  w = w_init
  b = b_init

  for i in range(num_iter):
    dj_dw, dj_db = gradient_function(x, y, w, b)
    w = w - alpha * dj_dw
    b = b - alpha * dj_db

    if i<100000:
      J_hist.append( cost_function(x, y, w, b))

    if i % math.ceil(num_iter/10) == 0:
      print(f"Iteration: {i}\t\t\tcost: {J_hist[i]:.3f}")

  return w, b, J_hist

In [ ]:
w_final, b_final, J_hist = gradient_descent(X_train, y_train, w_init, b_init, 0.00000083, 10000, compute_cost, compute_gradient)

Iteration: 0			cost: 533937.222
Iteration: 1000			cost: 86.284
Iteration: 2000			cost: 76.854
Iteration: 3000			cost: 68.717
Iteration: 4000			cost: 61.696
Iteration: 5000			cost: 55.638
Iteration: 6000			cost: 50.410
Iteration: 7000			cost: 45.899
Iteration: 8000			cost: 42.006
Iteration: 9000			cost: 38.646


In [ ]:
print(f"w_final: {w_final}")

print(f"Predicted value: {compute_multiple_linear_model(X_train, w_final, b_final)}\t\t\tActual value: {y_train}")

w_final: [  0.33658909  15.01142087 -45.05862182 -19.71285918]
Predicted value: [451.07876048 242.9883016  181.76355391]			Actual value: [460 232 178]
